### ISSUE TITLE
Can you upload bootloader and firmware on it?

### ISSUE THREAD

**Issue by DRCRecoveryData** [Zokhoi/mf3dre#1]
Hi,

If we made new pcb does it work on original firmware?

**Comment by Zokhoi** [comment]
That's what I'm hoping to achieve. However as the README has mentioned there are still some issues that can't be overlooked, even if you could get all the exact components right by transferring them from a working board. In specific, the issues are:
* the chip U11 and its related traces
* the footprint for the resistor networks R5, R6 and R7

Other than these, if you source new components, the capacitors and inductor values and led models are a problem too.

**Comment by DRCRecoveryData** [comment]
> That's what I'm hoping to achieve. However as the README has mentioned there are still some issues that can't be overlooked, even if you could get all the exact components right by transferring them from a working board. In specific, the issues are:
> * the chip U11 and its related traces
> * the footprint for the resistor networks R5, R6 and R7
> 
> Other than these, if you source new components, the capacitors and inductor values and led models are a problem too.

Can you open request to djtechtools:

support@djtechtools.com


to get the stock firmware upload file of midi fighter 3d via icsp pinout?

i have request them like this:

Hi,

I have set fuses wrong of midi fighter 64 via icsp port


I use avrduress and forgot to set fuses to 00 so can't detect again the atmega32u4


Should i buy new atmega32u4 chip and flash new bootloader and firmware?


I need your guide and bootloader & firmware & fuses bit value setting
to repair it

and they sent firmware file and tutorial upload by:


Setup
1. Instal WinAVR (avrdude)
2. Instal Drivers for the USBTiny Pocket Programmer
3. Set slide switch on the USB Pocket Programmer to "No Power"
4. Open Command Prompt, type "avrdude". You should see the version and the options listed

Uploading HEX
1. Connect the MF64_V3 PCB to the PC with a USB cable
2. Connect the USB Pocket Programmer as shown in the picture
3. Make sure all the programing pins are in contact with the PCB. You can put a little pressure on the programmer cable with your thumb to ensure a good connection.
4. Double click "AVRDude - Upload HEX.bat"
5. HEX will upload, LED's will cycle RED, GREEN, BLUE. All LED's should be lit, on all colors.
6. Remove the 6 pin programming header
7. Remove the MF64_V3 PCB USB connection

Possible Errors:
1. If USBTiny cannot be found when uploading HEX, unplug and replug the USBTiny Pocket Programmer

maybe you can help to request they sent stock file :)) 
usb tiny they use it's:


![image](https://github.com/Zokhoi/mf3dre/assets/85211068/61c501ed-24e3-48ca-b76e-cc3dc5ebf72a)

**Comment by Zokhoi** [comment]
If you have midifighter utility installed, I think you can find the mf3d firmware binary in the internal files.

I have previously sent a support ticket asking for mf3d firmware source code, they replied they did not have plans to release the source code at the time though.

**Comment by DRCRecoveryData** [comment]
> If you have midifighter utility installed, I think you can find the mf3d firmware binary in the internal files.
> 
> I have previously sent a support ticket asking for mf3d firmware source code, they replied they did not have plans to release the source code at the time though.

No the factory files is difference they use to set fuses,...

Just ask they new reuqest like me to get the bootloader and fw files because factory they have them, do you use discord telegram or any platform i wanna contact you

**Comment by Zokhoi** [comment]
My discord is same as my username.

**Comment by DRCRecoveryData** [comment]
> My discord is same as my username.

can you sent you discord link?

**Comment by DRCRecoveryData** [comment]
> That's what I'm hoping to achieve. However as the README has mentioned there are still some issues that can't be overlooked, even if you could get all the exact components right by transferring them from a working board. In specific, the issues are:
> * the chip U11 and its related traces
> * the footprint for the resistor networks R5, R6 and R7
> 
> Other than these, if you source new components, the capacitors and inductor values and led models are a problem too.

U11 is IST8308![image](https://github.com/Zokhoi/mf3dre/assets/85211068/2f19a631-46ea-48c0-bd66-699d25952bfc)
