### ISSUE TITLE
Custom Firmware

### ISSUE THREAD

**Issue by BoukeG** [Zokhoi/mf3dre#2]
In relation to writing the default firmware - have you been able to write some custom firmware?

**Comment by Zokhoi** [comment]
I haven't gotten around to that unfortunately. However some other Midi Fighter models have their firmware source code available, so you might want to reference those as your starting point.

My personal suggestion is to start by looking at [Midi Fighter 64](https://github.com/wunnation/Midi_Fighter_64) which has the same MCU, but no devices on the I2C bus. Older 16-button Midi Fighters source code [are also available](https://github.com/DJ-TechTools), but no spectra source code.

**Comment by BoukeG** [comment]
Cool, thanks - I'll have a look.
